[connections.gsheets]
type = "gsheets"
spreadsheet = "1xorAPoWd81bUE2yeJN4QsEhpEoUZ5yvdGIm2h9MHbkQ"

[google_service_account]
type = "service_account"
project_id = "jovial-engine-182800"
private_key_id = "a6bcb551f39a442bc787ececc254c4d3aaefe2f0"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDvgC2DOKs/iyxL
7NfmAAnMlfQqxVWGNUEef7VdrJDDLp4QU/OEE5ClaemA9e6cbpPcP6ZFf7otOjfZ
byimfpimCMITWGQoCqvz8ae98barlXajQE9RTHCYVJEij0y5MjHp6s7ye5cLmetB
FAzeDLvYTaldctgvihYiZuQ68ucWEcaz3ovzxGtUro8jiFQsYojHU5x2Gz7MFJqD
UYF3pjvzmbHrtZRYSM/qD1MQEYUAlWpPC2iN5x7wlT7+YcBJ96lefNk7pRotkOOL
qH3DjHNQywo7sg9YQqPnJ2UPyOEVxPgGtohOgSSN+GFvgBJroY4QPcNleCuRZy0N
ZU+sPOVTAgMBAAECggEASaMJW00zKehqiDWb8/WTDboVRolB0G/TQ8NUSibio4BT
zQVi2/sAADveNW5oHOTKxW80ei3ZWkqKHWpV/0rxOCt9MGF++ei+EdT9FCObXIop
3evJ918fR1bJAO06U76hJiCx3FAvkruSX4IAqs0TfF/0cOz8lzFHuPAVwCIq9teM
EVnRRuzz1RqVryB115uY5c0/JBRx7ATtXlF3cNZ4HhAxYD5K03U4wz/90TgwJVU5
/gGkn5fLITwOhDs+dyvRBb+bBGbjneTHpoRyDXRKSPRAHY8AA1B2m6PJb37WVLei
tYKM4B198ZFcLGK1056z4kNiUQCVNfcEgdtkXvktcQKBgQD5xrbf06x9YOgXRJH/
C8ujRBGQ0Gpn831aRgfIM4d+xBufz1tytUWktlSwDFDJoQH1ezYAd49W0GhLP4oo
dp1h8kVE2HBkRre/ZUJ2qpNCUEZTTaxv+V2DIPgWGuZR8OUTgWclb8SOSQQBXdxu
qHutTxsiv7+FSJFn16g7B+5gLQKBgQD1d+rVjwczUbvpz3xuYicjsn4GcmT3d0MN
RxXduYnG3BhDJTlj9WOewhan+sICraRJNZAbaUykqp3S8DC4ci70Fdesussb1Z2W
WVFc1Iqc5mqHfifNvShwR2mB/OKwO5dOIhh/N/HLKIfA1Mw9w8BFnhreyz1Vusse
KD9aFMZLfwKBgGby5IU0ta+ntYGBnbtFnVVZxPOvM2xNC6mdm6+EraAuLESeLs8E
sAPHsvgs209/sVMAya0/mjDqDVKWiddLrGqmdK5/lzN9gla84bwPakq204WaSiyM
12IowJg71hqH86Mqft0LSDRtG92EVkq13uP76u9ToRjKZEQsuwY5qqKxAoGBAOIJ
bBD95TaHtE+oxb9r2PjRO6W6H2mVxAPtCqCjYtDhCeKC26dFZ1fhCDXk/lSzC05y
6WGkhHQ5vJ1qmqKuWrhfiLxBQhk+ix/Q3dBq072JnF1qeULGRf+mcuzFLwXzye+k
DATSQnC+wMt76RuTL3GsFrhEVRWlrbb2fuf3q2YHAoGAXAhsvYxyLmOCPFPo0tc1
nLg0KJECusTGmbwzneJT7jkJYt2yG5i+ypbqzpbTIbEga3kXRQC+HcOYYpmrgsfQ
Da8Y82mrFRmr2QX6vfSzDdsjYwe5s+9XFq7UJHB/az4w5nEP21SmKQGaGG8AmG2H
vnI2sw8VEf8CqQPIL8MVrHs=
-----END PRIVATE KEY-----"""
client_email = "labreagentinventary@jovial-engine-182800.iam.gserviceaccount.com"
client_id = "109791162958811973767"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/labreagentinventary%40jovial-engine-182800.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
